spring:
  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:mariadb://localhost:3306/jpa
    username: root
    password: 4042

  second-datasource:
#    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:sqlserver://localhost:1433;database=sample
    username: local
    password: 4042